//---------------------------------------------------------------------------
#ifndef mainH
#define mainH
//---------------------------------------------------------------------------
#include "ALed.hpp"
#include "HTray.h"
#include "MyLed.h"
#include <ActnList.hpp>
#include <Buttons.hpp>
#include <Classes.hpp>
#include <ComCtrls.hpp>
#include <Controls.hpp>
#include <ExtCtrls.hpp>
#include <Grids.hpp>
#include <Menus.hpp>
#include <StdCtrls.hpp>

#include "CSMCDEF.H"
#include <Forms.hpp>
#include <Graphics.hpp>
#include "cmydef.h"
#include "FileInfo.h"
AnsiString DecodeStr(AnsiString sourceStr); //jou 2013-01-04 Password Txt 加密
//Click Event,Auto Save log
//==>
//---------------------------------------------------------------------------
class TMyProc
{
private:    // User declarations
public:     // User declarations
    AnsiString asOwnName;                                                       //記錄元件名稱//
    TWndMethod OldWinProc;
    AnsiString asCaption;
    AnsiString asOwner;
    void __fastcall MyMessage(TMessage & Message) ;
};
//---------------------------------------------------------------------------
//<==
//Click Event,Auto Save log
//---------------------------------------------------------------------------
class TfMain : public TForm
{
__published:    // IDE-managed Components
    TPageControl *pgcMain;
    TTabSheet *tsMain;
    TTabSheet *tsMonitorView;
    TPanel *pnlMain;
    TPanel *pnlMainMenu;
    TSpeedButton *sbLaguage;
    TActionList *FormShowList;
    TAction *ProgramStartDisplaySetup;
    TAction *ProgramStartLoadSystemINI;
    TAction *ProgramStartSetupAfterLoad;
    TPopupMenu *PopupMenu1;
        TSpeedButton *sbProduct;
        TSpeedButton *sbMaintance;
        TSpeedButton *sbOffset;
        TSpeedButton *sbSpeed;
        TSpeedButton *sbTool;
        TSpeedButton *sbMessage;
        TSpeedButton *sbExit;
        TSpeedButton *sbMonitor;
    TPanel *pnlMonitorView;
    TPanel *pnlMonitorMenu;
        TSpeedButton *sbRecord;
        TSpeedButton *sbMotorView;
        TSpeedButton *sbMotionView;
        TSpeedButton *sbOther;
    TSpeedButton *btnMainShow;
    TPageControl *pgcMonitor;
    TTabSheet *TabSheet7;
    TTabSheet *TabSheet10;
    TStringGrid *sgMotorStatus;
    TTimer *Timer1;
    TPanel *pnlControlBtn;
        TSpeedButton *sbHome1;
        TSpeedButton *sbStart1;
        TSpeedButton *sbPause1;
        TSpeedButton *sbRetry1;
        TSpeedButton *sbSkip1;
    TSpeedButton *sbTrayEnd1;
        TSpeedButton *sbTrayFeed1;
        TSpeedButton *sbOneCycle1;
        TSpeedButton *sbCleanOut1;
        TSpeedButton *sbReset1;
    TTabSheet *TabRecord;
    TTabSheet *TabOther;
    TPanel *Panel12;
    TPanel *Panel13;
    TPageControl *PageControl3;
    TTabSheet *TabSheet2;
    TStringGrid *StringGridLockInfo;
        TSpeedButton *sbStoreHangup;
        TPanel *PanelMain6;
    TPanel *pnlLed;
        TALed *ledRed1;
        TALed *ledYellow1;
        TALed *ledGreen1;
    TPanel *pnlPillar;
    TTabSheet *TabSheet13;
    TMemo *Memo2;
    TButton *Button2;
    TButton *Button4;
    TPageControl *PageControlTaskView;
    TTabSheet *tsTaskRecord;
    TListBox *lbTaskRecord;
    TPanel *pnlBinCntInfo;
    TPanel *pnlMain1;
    TPageControl *pgcLog;
    TTabSheet *tsTrayStatus;
    TTabSheet *tsLogs;
    TSpeedButton *sbHome;
    TSpeedButton *sbStart;
    TSpeedButton *sbPause;
    TSpeedButton *sbRetry;
    TSpeedButton *sbSkip;
    TSpeedButton *sbTrayEnd;
    TSpeedButton *sbTrayFeed;
    TSpeedButton *sbOneCycle;
    TSpeedButton *sbCleanOut;
    TSpeedButton *sbReset;
    TListBox *lstLog;
    TPanel *pnlLogMenu;
    TSpeedButton *spbTrayStatus;
    TPanel *pnlMain2;
    TLabel *lbl_WorkFile;
    TLabel *lblUserSelect;
    TComboBox *cbbUserSelect;
    TPanel *pnlSetting;
    TLabel *lblRunMode;
    TSpeedButton *sbDummyIcon;
    TSpeedButton *sbRealIcon;
    TSpeedButton *sbContinue;
    TSpeedButton *sbInitial;
    TPanel *pnlLight;
    TALed *ledYellow;
    TALed *ledRed;
    TALed *ledGreen;
    TPanel *pnRealDummy;
    TPanel *pnStartMode;
    TComboBox *cb_WorkFile;
    TPanel *palMainStatus;
    TLabel *lbCheckSafeDoorDisable;
    TStatusBar *statMain;
    TPanel *palClearBtn;
    TTabSheet *tsIOStatus;
    TMemo *memoIOStatus;
    TTabSheet *TabSuckStatus;
    TMemo *memoSuckStatus;
    TLabel *labTryRun;
    TTabSheet *tsTimeData;
    TStringGrid *sgTimeData;
    TSpeedButton *sbTimeData;
    TPanel *btSaveTimeData;
    TSpeedButton *btnTimeEvent;
    TPanel *palMainStatus_En;
    TLabel *labSECSOnOff;
    TPanel *pnlAuto1PathR;
    TPanel *palWorkEmpty1;
    TTMyTray *mtWorkEmpty1;
    TPanel *palEmpty1Car;
    TTMyTray *mtEmptyCar;
    TPanel *pnlAuto1PathL;
    TTimer *Timer2;
    TSpeedButton *apbLogs;
    TTabSheet *tsStripPos;
    TPageControl *PageControl4;
    TTabSheet *TabSheet4;
    TTabSheet *TabSheet5;
    TTabSheet *TabSheet6;
    TTabSheet *TabSheet8;
    TSpeedButton *spbStripPos;
    TScrollBox *ScrollBox1;
    TTMyTray *TMyTray1;
    TScrollBox *ScrollBox2;
    TTMyTray *TMyTray2;
    TScrollBox *ScrollBox3;
    TTMyTray *TMyTray3;
    TScrollBox *ScrollBox4;
    TTMyTray *TMyTray4;
    TTimer *tmrProductInfo;
    TCheckBox *cbCCDStep;
    TLabel *labCCDStep;
    TTimer *tmrDownCCDTrigger;
    TTabSheet *tsOffset;
    TMemo *MemoOffset;
    TCheckBox *cdStep;
    TTMyTray *TMyTray5;
    TTMyTray *TMyTray6;
    TTMyTray *TMyTray7;
    TTMyTray *TMyTray8;
    TTabSheet *TabSheet3;
    TMemo *MemoDownCCD;
    TMemo *MemoTopCCD;
    TLabel *lbStartMode;
    TMemo *MemoAudioCCD;
    TTabSheet *TabSheet9;
    TMemo *MemoEventLog;
    TButton *Button1;
    TPanel *Panel1;
    TPanel *palWorkLoader;
    TTMyTray *mtWorkLoader;
    TPanel *Panel5;
    TPanel *palShiftStage;
    TTMyTray *mtShiftStage;
    TPanel *Panel51;
    TPanel *Panel3;
    TPanel *Panel11;
    TPanel *Panel14;
    TPanel *palAuto16;
    TTMyTray *mtAuto16;
    TPanel *palAuto17;
    TTMyTray *mtAuto17;
    TPanel *palAuto18;
    TTMyTray *mtAuto18;
    TPanel *palAuto19;
    TTMyTray *mtAuto19;
    TPanel *palAuto20;
    TTMyTray *mtAuto20;
    TPanel *Panel20;
    TPanel *palAuto11;
    TTMyTray *mtAuto11;
    TPanel *palAuto12;
    TTMyTray *mtAuto12;
    TPanel *palAuto13;
    TTMyTray *mtAuto13;
    TPanel *palAuto14;
    TTMyTray *mtAuto14;
    TPanel *palAuto15;
    TTMyTray *mtAuto15;
    TPanel *palAuto07;
    TTMyTray *mtAuto07;
    TPanel *palAuto08;
    TTMyTray *mtAuto08;
    TPanel *palAuto09;
    TTMyTray *mtAuto09;
    TPanel *palAuto10;
    TTMyTray *mtAuto10;
    TPanel *palAuto02;
    TTMyTray *mtAuto02;
    TPanel *palAuto03;
    TTMyTray *mtAuto03;
    TPanel *palAuto04;
    TTMyTray *mtAuto04;
    TPanel *palAuto05;
    TTMyTray *mtAuto05;
    TPanel *palAuto06;
    TTMyTray *mtAuto06;
    TPanel *palAuto01;
    TTMyTray *mtAuto01;
    TPanel *Panel29;
    TPanel *Panel30;
    TPanel *Panel31;
    TPanel *palMagNowSortTray;
    TTMyTray *mtMagNowSortTray;
    TPanel *palEmpty2Car;
    TTMyTray *mtMagEmpty_Car;
    TPanel *Panel34;
    TPanel *palMagLD;
    TTMyTray *mtMagLD;
    TPanel *Panel35;
    TPanel *Panel36;
    TPanel *Panel37;
    TPanel *Panel39;
    TPanel *palAutoStore20;
    TPanel *palAutoStore19;
    TPanel *palAutoStore18;
    TPanel *palAutoStore17;
    TPanel *palAutoStore16;
    TPanel *palAutoStore15;
    TPanel *palAutoStore14;
    TPanel *palAutoStore13;
    TPanel *palAutoStore12;
    TPanel *palAutoStore11;
    TPanel *palAutoStore10;
    TPanel *palAutoStore09;
    TPanel *palAutoStore08;
    TPanel *palAutoStore07;
    TPanel *palAutoStore06;
    TPanel *palAutoStore05;
    TPanel *palAutoStore04;
    TPanel *palAutoStore03;
    TPanel *palAutoStore02;
    TPanel *palAutoStore01;
    TPanel *Panel67;
    TPanel *palMag3;
    TTMyTray *mtMag3;
    TPanel *palMag1;
    TTMyTray *mtMag1;
    TPanel *palMag2;
    TTMyTray *mtMag2;
    TPanel *Panel4;
    TPanel *palTrayArm;
    TMyLed *ledTrayArm;
    TPanel *Panel6;
    TPanel *Panel7;
    TLabel *Label1;
    TSpeedButton *btnClearCount;
    TPanel *palloadingCount;
    TPanel *palUnloadingCount;
    TLabel *lblUnloadingCount;
    TLabel *lblloseCnt;
    TPanel *palloseCnt;
    TPanel *Panel149;
    TPanel *Panel150;
    TPanel *palSortArm1;
    TMyLed *ledSortArm1ZA;
    TMyLed *ledSortArm1ZB;
    TMyLed *ledSortArm1ZC;
    TMyLed *ledSortArm1ZD;
    TMyLed *ledSortArm1ZE;
    TMyLed *ledSortArm1ZF;
    TMyLed *ledSortArm1ZG;
    TMyLed *ledSortArm1ZH;
    TPanel *palSortArm2;
    TMyLed *ledSortArm2ZA;
    TMyLed *ledSortArm2ZC;
    TMyLed *ledSortArm2ZE;
    TMyLed *ledSortArm2ZG;
    TMyLed *ledSortArm2ZB;
    TMyLed *ledSortArm2ZD;
    TMyLed *ledSortArm2ZF;
    TMyLed *ledSortArm2ZH;
    TPanel *Panel152;
    TPanel *Panel153;
    TTabSheet *tsMapTray;
    TSpeedButton *btnTrayMap;
    TPanel *palNowSortTray;
    TTMyTray *mtNowSortTray;
    TPanel *palWorkEmpty2;
    TTMyTray *mtWorkEmpty2;
    TPanel *palWorkEmpty3;
    TTMyTray *mtWorkEmpty3;
    TPanel *palWorkEmpty4;
    TTMyTray *mtWorkEmpty4;
    TPanel *palMagEmptyTray;
    TTMyTray *mtMagEmptyTray;
    TPanel *Panel73;
    TPanel *palTrack1TrayArm;
    TTMyTray *mtTrack1TrayArm;
    TPanel *palTrack2TrayArm;
    TTMyTray *mtTrack2TrayArm;
    TPanel *palTrack3TrayArm;
    TTMyTray *mtTrack3TrayArm;
    TPanel *palTrack4TrayArm;
    TTMyTray *mtTrack4TrayArm;
    TPanel *pnlMgz2;
    TLabel *labAuto20;
    TLabel *labAuto19;
    TLabel *labAuto18;
    TLabel *labAuto17;
    TLabel *labAuto16;
    TLabel *labAuto15;
    TLabel *labAuto14;
    TLabel *labAuto13;
    TLabel *labAuto12;
    TLabel *labAuto11;
    TLabel *labAuto10;
    TLabel *labAuto09;
    TLabel *labAuto08;
    TLabel *labAuto07;
    TLabel *labAuto06;
    TLabel *labAuto05;
    TLabel *labAuto04;
    TLabel *labAuto03;
    TLabel *labAuto02;
    TLabel *labAuto01;
    TPanel *pnlSafePLC;
    TALed *ledSafePLC;
    TLabel *LoaderClipID;
    TPanel *palMagBuf2;
    TTMyTray *mtMagBuf2;
    TPanel *palMagBuf1;
    TTMyTray *mtMagBuf1;
    TPanel *palMagBuf3;
    TTMyTray *mtMagBuf3;
    TPanel *palMagTrayArm;
    TMyLed *ledMagTrayArm;
    TEdit *edtULDAuto;
    TPanel *Panel2;
    TSpeedButton *sbPaperSummary;
    TMemo *MemoBinCount;
    TGroupBox *grpLoader;
    TTMyTray *mtSortRecv;
    TGroupBox *grpWorkArea;
    TTMyTray *mtWorkArea;
    TGroupBox *grpMgz;
    TTMyTray *mtMgzArea;
    TButton *btnClearTray;
    TButton *btnSetBinMatrix;
    TLabeledEdit *edtTrayID;
    TLabel *lblMgzCurrBin_1;
    TLabel *lblLoadCurrBin_1;
    TPanel *palLoadCar;
    TTMyTray *mtLoaderCar;
    TMyLed *ledLoad;
    TCheckBox *chkLoadTray;
    TLabel *lblLoadCurrBin_2;
    TLabel *lblMgzCurrBin_2;
    TPanel *Panel8;
    TMyLed *ledEmpty1;
    TMyLed *ledEmpty2;
    TCheckBox *chkLoadEmpty1Tray;
    TCheckBox *chkLoadEmpty2Tray;
    TPanel *Panel9;
    TGroupBox *grpTrack1;
    TGroupBox *grpTrack2;
    TGroupBox *grpTrack3;
    TGroupBox *grpTrack4;
    TPanel *Panel10;
    TPanel *pnlMgzTop;
    TPageControl *pgcMgzCnt;
    TTabSheet *tsMgz1;
    TTabSheet *tsMgz2;
    TTabSheet *tsMgz3;
    TLabel *lblMgzTop2;
    TPanel *pnlMgz2TopBin;
    TLabel *lblMgzTop3;
    TPanel *pnlMgz3TopBin;
    TPanel *palMag2_01Cn;
    TPanel *palMag2_05Cn;
    TPanel *palMag2_02Cn;
    TPanel *palMag2_04Cn;
    TPanel *palMag2_03Cn;
    TPanel *palMag2_06Cn;
    TPanel *palMag2_07Cn;
    TPanel *palMag2_09Cn;
    TPanel *palMag2_08Cn;
    TPanel *palMag2_10Cn;
    TPanel *palMag2_11Cn;
    TPanel *palMag2_13Cn;
    TPanel *palMag2_12Cn;
    TPanel *palMag2_14Cn;
    TPanel *palMag2_15Cn;
    TPanel *palMag2_19Cn;
    TPanel *palMag2_16Cn;
    TPanel *palMag2_18Cn;
    TPanel *palMag2_17Cn;
    TPanel *palMag2_20Cn;
    TPanel *palMag2_21Cn;
    TPanel *palMag2_23Cn;
    TPanel *palMag2_22Cn;
    TPanel *palMag2_24Cn;
    TPanel *palMag2_01Bin;
    TPanel *palMag2_05Bin;
    TPanel *palMag2_02Bin;
    TPanel *palMag2_04Bin;
    TPanel *palMag2_03Bin;
    TPanel *palMag2_06Bin;
    TPanel *palMag2_07Bin;
    TPanel *palMag2_09Bin;
    TPanel *palMag2_08Bin;
    TPanel *palMag2_10Bin;
    TPanel *palMag2_11Bin;
    TPanel *palMag2_13Bin;
    TPanel *palMag2_12Bin;
    TPanel *palMag2_14Bin;
    TPanel *palMag2_15Bin;
    TPanel *palMag2_19Bin;
    TPanel *palMag2_16Bin;
    TPanel *palMag2_18Bin;
    TPanel *palMag2_17Bin;
    TPanel *palMag2_20Bin;
    TPanel *palMag2_21Bin;
    TPanel *palMag2_23Bin;
    TPanel *palMag2_22Bin;
    TPanel *palMag2_24Bin;
    TPanel *palMag2_25Cn;
    TPanel *palMag2_27Cn;
    TPanel *palMag2_26Cn;
    TPanel *palMag2_25Bin;
    TPanel *palMag2_27Bin;
    TPanel *palMag2_26Bin;
    TPanel *palMgz2_01ID;
    TPanel *palMgz2_05ID;
    TPanel *palMgz2_02ID;
    TPanel *palMgz2_04ID;
    TPanel *palMgz2_03ID;
    TPanel *palMgz2_06ID;
    TPanel *palMgz2_07ID;
    TPanel *palMgz2_09ID;
    TPanel *palMgz2_08ID;
    TPanel *palMgz2_10ID;
    TPanel *palMgz2_11ID;
    TPanel *palMgz2_13ID;
    TPanel *palMgz2_12ID;
    TPanel *palMgz2_14ID;
    TPanel *palMgz2_15ID;
    TPanel *palMgz2_19ID;
    TPanel *palMgz2_16ID;
    TPanel *palMgz2_18ID;
    TPanel *palMgz2_17ID;
    TPanel *palMgz2_20ID;
    TPanel *palMgz2_21ID;
    TPanel *palMgz2_23ID;
    TPanel *palMgz2_22ID;
    TPanel *palMgz2_24ID;
    TPanel *palMgz2_25ID;
    TPanel *palMgz2_27ID;
    TPanel *palMgz2_26ID;
    TPanel *lblLoaderCarID;
    TPanel *lblLoadCurrID_1;
    TPanel *lblMgzCurrID_1;
    TCheckBox *chkLoadMatrix;
    TLabeledEdit *edtEmpty2ID;
    TPanel *pnlMgz2TopID;
    TPanel *pnlMgz3TopID;
    TStringGrid *sgProductInfo;
    TButton *btnClearMgz2;
    TMemo *Memo1;
    TPanel *palMag2TopCnt;
    TPanel *palMag3TopCnt;
    TLabel *lblMgz201Cnt;
    TLabel *lblMgz205Cnt;
    TLabel *lblMgz202Cnt;
    TLabel *lblMgz204Cnt;
    TLabel *lblMgz203Cnt;
    TLabel *lblMgz206Cnt;
    TLabel *lblMgz207Cnt;
    TLabel *lblMgz209Cnt;
    TLabel *lblMgz208Cnt;
    TLabel *lblMgz210Cnt;
    TLabel *lblMgz211Cnt;
    TLabel *lblMgz212Cnt;
    TLabel *lblMgz214Cnt;
    TLabel *lblMgz213Cnt;
    TLabel *lblMgz215Cnt;
    TLabel *lblMgz219Cnt;
    TLabel *lblMgz216Cnt;
    TLabel *lblMgz218Cnt;
    TLabel *lblMgz217Cnt;
    TLabel *lblMgz220Cnt;
    TLabel *lblMgz221Cnt;
    TLabel *lblMgz223Cnt;
    TLabel *lblMgz222Cnt;
    TLabel *lblMgz224Cnt;
    TLabel *lblMgz225Cnt;
    TLabel *lblMgz226Cnt;
    TLabel *lblMgz227Cnt;
    TLabel *lblMgz101Cnt;
    TLabel *lblMgz105Cnt;
    TLabel *lblMgz102Cnt;
    TLabel *lblMgz104Cnt;
    TLabel *lblMgz103Cnt;
    TLabel *lblMgz106Cnt;
    TLabel *lblMgz107Cnt;
    TLabel *lblMgz109Cnt;
    TLabel *lblMgz108Cnt;
    TLabel *lblMgz110Cnt;
    TLabel *lblMgz111Cnt;
    TLabel *lblMgz112Cnt;
    TLabel *lblMgz114Cnt;
    TLabel *lblMgz113Cnt;
    TLabel *lblMgz115Cnt;
    TLabel *lblMgz119Cnt;
    TLabel *lblMgz116Cnt;
    TLabel *lblMgz118Cnt;
    TLabel *lblMgz117Cnt;
    TLabel *lblMgz120Cnt;
    TLabel *lblMgz121Cnt;
    TLabel *lblMgz123Cnt;
    TLabel *lblMgz122Cnt;
    TLabel *lblMgz124Cnt;
    TLabel *lblMgz125Cnt;
    TLabel *lblMgz126Cnt;
    TLabel *lblMgz127Cnt;
    TPanel *palMag1_01Cn;
    TPanel *palMag1_05Cn;
    TPanel *palMag1_02Cn;
    TPanel *palMag1_04Cn;
    TPanel *palMag1_03Cn;
    TPanel *palMag1_06Cn;
    TPanel *palMag1_07Cn;
    TPanel *palMag1_09Cn;
    TPanel *palMag1_08Cn;
    TPanel *palMag1_10Cn;
    TPanel *palMag1_11Cn;
    TPanel *palMag1_13Cn;
    TPanel *palMag1_12Cn;
    TPanel *palMag1_14Cn;
    TPanel *palMag1_15Cn;
    TPanel *palMag1_19Cn;
    TPanel *palMag1_16Cn;
    TPanel *palMag1_18Cn;
    TPanel *palMag1_17Cn;
    TPanel *palMag1_20Cn;
    TPanel *palMag1_21Cn;
    TPanel *palMag1_23Cn;
    TPanel *palMag1_22Cn;
    TPanel *palMag1_24Cn;
    TPanel *palMag1_01Bin;
    TPanel *palMag1_05Bin;
    TPanel *palMag1_02Bin;
    TPanel *palMag1_04Bin;
    TPanel *palMag1_03Bin;
    TPanel *palMag1_06Bin;
    TPanel *palMag1_07Bin;
    TPanel *palMag1_09Bin;
    TPanel *palMag1_08Bin;
    TPanel *palMag1_10Bin;
    TPanel *palMag1_11Bin;
    TPanel *palMag1_13Bin;
    TPanel *palMag1_12Bin;
    TPanel *palMag1_14Bin;
    TPanel *palMag1_15Bin;
    TPanel *palMag1_19Bin;
    TPanel *palMag1_16Bin;
    TPanel *palMag1_18Bin;
    TPanel *palMag1_17Bin;
    TPanel *palMag1_20Bin;
    TPanel *palMag1_21Bin;
    TPanel *palMag1_23Bin;
    TPanel *palMag1_22Bin;
    TPanel *palMag1_24Bin;
    TPanel *palMag1_25Cn;
    TPanel *palMag1_27Cn;
    TPanel *palMag1_26Cn;
    TPanel *palMag1_25Bin;
    TPanel *palMag1_27Bin;
    TPanel *palMag1_26Bin;
    TPanel *palMgz1_01ID;
    TPanel *palMgz1_05ID;
    TPanel *palMgz1_02ID;
    TPanel *palMgz1_04ID;
    TPanel *palMgz1_03ID;
    TPanel *palMgz1_06ID;
    TPanel *palMgz1_07ID;
    TPanel *palMgz1_09ID;
    TPanel *palMgz1_08ID;
    TPanel *palMgz1_10ID;
    TPanel *palMgz1_11ID;
    TPanel *palMgz1_13ID;
    TPanel *palMgz1_12ID;
    TPanel *palMgz1_14ID;
    TPanel *palMgz1_15ID;
    TPanel *palMgz1_19ID;
    TPanel *palMgz1_16ID;
    TPanel *palMgz1_18ID;
    TPanel *palMgz1_17ID;
    TPanel *palMgz1_20ID;
    TPanel *palMgz1_21ID;
    TPanel *palMgz1_23ID;
    TPanel *palMgz1_22ID;
    TPanel *palMgz1_24ID;
    TPanel *palMgz1_25ID;
    TPanel *palMgz1_27ID;
    TPanel *palMgz1_26ID;
    TLabel *lblMgz301Cnt;
    TLabel *lblMgz305Cnt;
    TLabel *lblMgz302Cnt;
    TLabel *lblMgz304Cnt;
    TLabel *lblMgz303Cnt;
    TLabel *lblMgz306Cnt;
    TLabel *lblMgz307Cnt;
    TLabel *lblMgz309Cnt;
    TLabel *lblMgz308Cnt;
    TLabel *lblMgz310Cnt;
    TLabel *lblMgz311Cnt;
    TLabel *lblMgz312Cnt;
    TLabel *lblMgz314Cnt;
    TLabel *lblMgz313Cnt;
    TLabel *lblMgz315Cnt;
    TLabel *lblMgz319Cnt;
    TLabel *lblMgz316Cnt;
    TLabel *lblMgz318Cnt;
    TLabel *lblMgz317Cnt;
    TLabel *lblMgz320Cnt;
    TLabel *lblMgz321Cnt;
    TLabel *lblMgz323Cnt;
    TLabel *lblMgz322Cnt;
    TLabel *lblMgz324Cnt;
    TLabel *lblMgz325Cnt;
    TLabel *lblMgz326Cnt;
    TLabel *lblMgz327Cnt;
    TPanel *palMag3_01Cn;
    TPanel *palMag3_05Cn;
    TPanel *palMag3_02Cn;
    TPanel *palMag3_04Cn;
    TPanel *palMag3_03Cn;
    TPanel *palMag3_06Cn;
    TPanel *palMag3_07Cn;
    TPanel *palMag3_09Cn;
    TPanel *palMag3_08Cn;
    TPanel *palMag3_10Cn;
    TPanel *palMag3_11Cn;
    TPanel *palMag3_13Cn;
    TPanel *palMag3_12Cn;
    TPanel *palMag3_14Cn;
    TPanel *palMag3_15Cn;
    TPanel *palMag3_19Cn;
    TPanel *palMag3_16Cn;
    TPanel *palMag3_18Cn;
    TPanel *palMag3_17Cn;
    TPanel *palMag3_20Cn;
    TPanel *palMag3_21Cn;
    TPanel *palMag3_23Cn;
    TPanel *palMag3_22Cn;
    TPanel *palMag3_24Cn;
    TPanel *palMag3_01Bin;
    TPanel *palMag3_05Bin;
    TPanel *palMag3_02Bin;
    TPanel *palMag3_04Bin;
    TPanel *palMag3_03Bin;
    TPanel *palMag3_06Bin;
    TPanel *palMag3_07Bin;
    TPanel *palMag3_09Bin;
    TPanel *palMag3_08Bin;
    TPanel *palMag3_10Bin;
    TPanel *palMag3_11Bin;
    TPanel *palMag3_13Bin;
    TPanel *palMag3_12Bin;
    TPanel *palMag3_14Bin;
    TPanel *palMag3_15Bin;
    TPanel *palMag3_19Bin;
    TPanel *palMag3_16Bin;
    TPanel *palMag3_18Bin;
    TPanel *palMag3_17Bin;
    TPanel *palMag3_20Bin;
    TPanel *palMag3_21Bin;
    TPanel *palMag3_23Bin;
    TPanel *palMag3_22Bin;
    TPanel *palMag3_24Bin;
    TPanel *palMag3_25Cn;
    TPanel *palMag3_27Cn;
    TPanel *palMag3_26Cn;
    TPanel *palMag3_25Bin;
    TPanel *palMag3_27Bin;
    TPanel *palMag3_26Bin;
    TPanel *palMgz3_01ID;
    TPanel *palMgz3_05ID;
    TPanel *palMgz3_02ID;
    TPanel *palMgz3_04ID;
    TPanel *palMgz3_03ID;
    TPanel *palMgz3_06ID;
    TPanel *palMgz3_07ID;
    TPanel *palMgz3_09ID;
    TPanel *palMgz3_08ID;
    TPanel *palMgz3_10ID;
    TPanel *palMgz3_11ID;
    TPanel *palMgz3_13ID;
    TPanel *palMgz3_12ID;
    TPanel *palMgz3_14ID;
    TPanel *palMgz3_15ID;
    TPanel *palMgz3_19ID;
    TPanel *palMgz3_16ID;
    TPanel *palMgz3_18ID;
    TPanel *palMgz3_17ID;
    TPanel *palMgz3_20ID;
    TPanel *palMgz3_21ID;
    TPanel *palMgz3_23ID;
    TPanel *palMgz3_22ID;
    TPanel *palMgz3_24ID;
    TPanel *palMgz3_25ID;
    TPanel *palMgz3_27ID;
    TPanel *palMgz3_26ID;
    TTMyTray *mtMagBin201;
    TTMyTray *mtMagBin202;
    TTMyTray *mtMagBin203;
    TTMyTray *mtMagBin204;
    TTMyTray *mtMagBin205;
    TTMyTray *mtMagBin206;
    TTMyTray *mtMagBin207;
    TTMyTray *mtMagBin208;
    TTMyTray *mtMagBin209;
    TTMyTray *mtMagBin210;
    TTMyTray *mtMagBin211;
    TTMyTray *mtMagBin212;
    TTMyTray *mtMagBin213;
    TTMyTray *mtMagBin214;
    TTMyTray *mtMagBin215;
    TTMyTray *mtMagBin216;
    TTMyTray *mtMagBin217;
    TTMyTray *mtMagBin218;
    TTMyTray *mtMagBin219;
    TTMyTray *mtMagBin220;
    TTMyTray *mtMagBin221;
    TTMyTray *mtMagBin222;
    TTMyTray *mtMagBin223;
    TTMyTray *mtMagBin224;
    TTMyTray *mtMagBin225;
    TTMyTray *mtMagBin226;
    TTMyTray *mtMagBin227;
    TPanel *pnlMgz1;
    TTMyTray *mtMagBin101;
    TTMyTray *mtMagBin102;
    TTMyTray *mtMagBin103;
    TTMyTray *mtMagBin104;
    TTMyTray *mtMagBin105;
    TTMyTray *mtMagBin106;
    TTMyTray *mtMagBin107;
    TTMyTray *mtMagBin108;
    TTMyTray *mtMagBin109;
    TTMyTray *mtMagBin110;
    TTMyTray *mtMagBin111;
    TTMyTray *mtMagBin112;
    TTMyTray *mtMagBin113;
    TTMyTray *mtMagBin114;
    TTMyTray *mtMagBin115;
    TTMyTray *mtMagBin116;
    TTMyTray *mtMagBin117;
    TTMyTray *mtMagBin118;
    TTMyTray *mtMagBin119;
    TTMyTray *mtMagBin120;
    TTMyTray *mtMagBin121;
    TTMyTray *mtMagBin122;
    TTMyTray *mtMagBin123;
    TTMyTray *mtMagBin124;
    TTMyTray *mtMagBin125;
    TTMyTray *mtMagBin126;
    TTMyTray *mtMagBin127;
    TPanel *pnlMgz3;
    TTMyTray *mtMagBin301;
    TTMyTray *mtMagBin302;
    TTMyTray *mtMagBin303;
    TTMyTray *mtMagBin304;
    TTMyTray *mtMagBin305;
    TTMyTray *mtMagBin306;
    TTMyTray *mtMagBin307;
    TTMyTray *mtMagBin308;
    TTMyTray *mtMagBin309;
    TTMyTray *mtMagBin310;
    TTMyTray *mtMagBin311;
    TTMyTray *mtMagBin312;
    TTMyTray *mtMagBin313;
    TTMyTray *mtMagBin314;
    TTMyTray *mtMagBin315;
    TTMyTray *mtMagBin316;
    TTMyTray *mtMagBin317;
    TTMyTray *mtMagBin318;
    TTMyTray *mtMagBin319;
    TTMyTray *mtMagBin320;
    TTMyTray *mtMagBin321;
    TTMyTray *mtMagBin322;
    TTMyTray *mtMagBin323;
    TTMyTray *mtMagBin324;
    TTMyTray *mtMagBin325;
    TTMyTray *mtMagBin326;
    TTMyTray *mtMagBin327;
    TLabel *lblMgzTop1;
    TPanel *pnlMgz1TopBin;
    TPanel *pnlMgz1TopID;
    TPanel *palMag1TopCnt;
    TButton *btnClearMgz3;
    TButton *btnClearMgz1;
    TCheckBox *cbMagStep;
    TButton *btnClearNowLoad;
    TButton *btnClearNowMag;
    TButton *btnRandom;
    TEdit *edRandom;
    TGroupBox *GroupBox1;
    TLabel *lblLotNo;
    TLabel *labWaferLot;
    TLabel *labCusDevice;
    TLabel *labInsettion;
    TLabel *labFlowID;
    TLabel *labOP;
    TEdit *edLotNo;
    TButton *btnLotStart;
    TButton *btnLotEnd;
    TEdit *edWaferLot;
    TEdit *edCusDevice;
    TEdit *edInsertion;
    TEdit *edFlowID;
    TEdit *edOperator;
    TPanel *palMag1_01LotCnt;
    TPanel *palMag1_05LotCnt;
    TPanel *palMag1_02LotCnt;
    TPanel *palMag1_04LotCnt;
    TPanel *palMag1_03LotCnt;
    TPanel *palMag1_06LotCnt;
    TPanel *palMag1_07LotCnt;
    TPanel *palMag1_09LotCnt;
    TPanel *palMag1_08LotCnt;
    TPanel *palMag1_10LotCnt;
    TPanel *palMag1_11LotCnt;
    TPanel *palMag1_13LotCnt;
    TPanel *palMag1_12LotCnt;
    TPanel *palMag1_14LotCnt;
    TPanel *palMag1_15LotCnt;
    TPanel *palMag1_19LotCnt;
    TPanel *palMag1_16LotCnt;
    TPanel *palMag1_18LotCnt;
    TPanel *palMag1_17LotCnt;
    TPanel *palMag1_20LotCnt;
    TPanel *palMag1_21LotCnt;
    TPanel *palMag1_23LotCnt;
    TPanel *palMag1_22LotCnt;
    TPanel *palMag1_24LotCnt;
    TPanel *palMag1_25LotCnt;
    TPanel *palMag1_27LotCnt;
    TPanel *palMag1_26LotCnt;
    TPanel *palMag2_01LotCnt;
    TPanel *palMag2_05LotCnt;
    TPanel *palMag2_02LotCnt;
    TPanel *palMag2_04LotCnt;
    TPanel *palMag2_03LotCnt;
    TPanel *palMag2_06LotCnt;
    TPanel *palMag2_07LotCnt;
    TPanel *palMag2_09LotCnt;
    TPanel *palMag2_08LotCnt;
    TPanel *palMag2_10LotCnt;
    TPanel *palMag2_11LotCnt;
    TPanel *palMag2_13LotCnt;
    TPanel *palMag2_12LotCnt;
    TPanel *palMag2_14LotCnt;
    TPanel *palMag2_15LotCnt;
    TPanel *palMag2_19LotCnt;
    TPanel *palMag2_16LotCnt;
    TPanel *palMag2_18LotCnt;
    TPanel *palMag2_17LotCnt;
    TPanel *palMag2_20LotCnt;
    TPanel *palMag2_21LotCnt;
    TPanel *palMag2_23LotCnt;
    TPanel *palMag2_22LotCnt;
    TPanel *palMag2_24LotCnt;
    TPanel *palMag2_25LotCnt;
    TPanel *palMag2_27LotCnt;
    TPanel *palMag2_26LotCnt;
    TPanel *palMag3_01LotCnt;
    TPanel *palMag3_05LotCnt;
    TPanel *palMag3_02LotCnt;
    TPanel *palMag3_04LotCnt;
    TPanel *palMag3_03LotCnt;
    TPanel *palMag3_06LotCnt;
    TPanel *palMag3_07LotCnt;
    TPanel *palMag3_09LotCnt;
    TPanel *palMag3_08LotCnt;
    TPanel *palMag3_10LotCnt;
    TPanel *palMag3_11LotCnt;
    TPanel *palMag3_13LotCnt;
    TPanel *palMag3_12LotCnt;
    TPanel *palMag3_14LotCnt;
    TPanel *palMag3_15LotCnt;
    TPanel *palMag3_19LotCnt;
    TPanel *palMag3_16LotCnt;
    TPanel *palMag3_18LotCnt;
    TPanel *palMag3_17LotCnt;
    TPanel *palMag3_20LotCnt;
    TPanel *palMag3_21LotCnt;
    TPanel *palMag3_23LotCnt;
    TPanel *palMag3_22LotCnt;
    TPanel *palMag3_24LotCnt;
    TPanel *palMag3_25LotCnt;
    TPanel *palMag3_27LotCnt;
    TPanel *palMag3_26LotCnt;
    TPanel *palMag3TopLotCnt;
    TPanel *palMag2TopLotCnt;
    TPanel *palMag1TopLotCnt;
    TLabel *labRunCard;
    TEdit *edtRunCard;
    TTimer *Timer6;
    TButton *btnAlarmTest;
    TTabSheet *tsSingleAction;
    TGroupBox *GroupBox2;
    TSpeedButton *sb;
    TPanel *lblEmpty1_Track4ID;
    TPanel *lblEmpty1_Track3ID;
    TPanel *lblEmpty1_Track2ID;
    TPanel *lblEmpty1_Track1ID;
    TPanel *lblEmpty1_CarID;
    TPanel *lblEmpty2_CarID;
    TPanel *lblTransferID;
    TLabel *labAutomation;
    TLabel *lblLotInfo;
    TPanel *pal1;
    TStringGrid *UPH_StringGrid;
    TPanel *palAutoInfo16;
    TLabel *lblAuto16Cnt;
    TPanel *palAuto16Bin;
    TButton *btnSetFullTray_Auto16;
    TPanel *palAuto16ID;
    TPanel *palAuto16Cnt;
    TPanel *palAuto16LotCnt;
    TPanel *pnlAuto16ICCnt;
    TPanel *pnlAuto16EmptyCnt;
    TPanel *palAuto16In;
    TPanel *palAutoInfo18;
    TLabel *lblAuto18Cnt;
    TButton *btnSetFullTray_Auto18;
    TPanel *palAuto18Bin;
    TPanel *palAuto18ID;
    TPanel *palAuto18Cnt;
    TPanel *palAuto18LotCnt;
    TPanel *pnlAuto18EmptyCnt;
    TPanel *pnlAuto18ICCnt;
    TPanel *palAuto18In;
    TPanel *palAutoInfo19;
    TLabel *lblAuto19Cnt;
    TPanel *palAuto19Bin;
    TButton *btnSetFullTray_Auto19;
    TPanel *palAuto19ID;
    TPanel *palAuto19Cnt;
    TPanel *palAuto19LotCnt;
    TPanel *pnlAuto19EmptyCnt;
    TPanel *pnlAuto19ICCnt;
    TPanel *palAuto19In;
    TPanel *palAutoInfo20;
    TLabel *lblAuto20Cnt;
    TPanel *palAuto20Bin;
    TButton *btnSetFullTray_Auto20;
    TPanel *palAuto20ID;
    TPanel *palAuto20Cnt;
    TPanel *palAuto20LotCnt;
    TPanel *pnlAuto20EmptyCnt;
    TPanel *pnlAuto20ICCnt;
    TPanel *palAuto20In;
    TPanel *palAutoInfo17;
    TLabel *lblAuto17Cnt;
    TPanel *palAuto17Bin;
    TButton *btnSetFullTray_Auto17;
    TPanel *palAuto17ID;
    TPanel *palAuto17Cnt;
    TPanel *palAuto17LotCnt;
    TPanel *pnlAuto17ICCnt;
    TPanel *pnlAuto17EmptyCnt;
    TPanel *palAuto17In;
    TPanel *palAutoInfo11;
    TLabel *lblAuto11Cnt;
    TPanel *palAuto11Bin;
    TButton *btnSetFullTray_Auto11;
    TPanel *palAuto11ID;
    TPanel *palAuto11Cnt;
    TPanel *palAuto11LotCnt;
    TPanel *pnlAuto11ICCnt;
    TPanel *pnlAuto11EmptyCnt;
    TPanel *palAuto11In;
    TPanel *palAutoInfo12;
    TLabel *lblAuto12Cnt;
    TPanel *palAuto12Bin;
    TButton *btnSetFullTray_Auto12;
    TPanel *palAuto12ID;
    TPanel *palAuto12Cnt;
    TPanel *palAuto12LotCnt;
    TPanel *pnlAuto12EmptyCnt;
    TPanel *pnlAuto12ICCnt;
    TPanel *palAuto12In;
    TPanel *palAutoInfo13;
    TLabel *lblAuto13Cnt;
    TPanel *palAuto13Bin;
    TButton *btnSetFullTray_Auto13;
    TPanel *palAuto13ID;
    TPanel *palAuto13Cnt;
    TPanel *palAuto13LotCnt;
    TPanel *pnlAuto13EmptyCnt;
    TPanel *pnlAuto13ICCnt;
    TPanel *palAuto13In;
    TPanel *palAutoInfo14;
    TLabel *lblAuto14Cnt;
    TPanel *palAuto14Bin;
    TButton *btnSetFullTray_Auto14;
    TPanel *palAuto14ID;
    TPanel *palAuto14Cnt;
    TPanel *palAuto14LotCnt;
    TPanel *pnlAuto14EmptyCnt;
    TPanel *pnlAuto14ICCnt;
    TPanel *palAuto14In;
    TPanel *palAutoInfo15;
    TLabel *lblAuto15Cnt;
    TPanel *palAuto15Bin;
    TButton *btnSetFullTray_Auto15;
    TPanel *palAuto15ID;
    TPanel *palAuto15Cnt;
    TPanel *palAuto15LotCnt;
    TPanel *pnlAuto15ICCnt;
    TPanel *pnlAuto15EmptyCnt;
    TPanel *palAuto15In;
    TPanel *palAutoInfo06;
    TLabel *lblAuto06Cnt;
    TPanel *palAuto06Bin;
    TButton *btnSetFullTray_Auto6;
    TPanel *palAuto06ID;
    TPanel *palAuto06Cnt;
    TPanel *palAuto06LotCnt;
    TPanel *pnlAuto06EmptyCnt;
    TPanel *pnlAuto06ICCnt;
    TPanel *palAuto06In;
    TPanel *palAutoInfo07;
    TLabel *lblAuto07Cnt;
    TButton *btnSetFullTray_Auto7;
    TPanel *palAuto07Bin;
    TPanel *palAuto07ID;
    TPanel *palAuto07Cnt;
    TPanel *palAuto07LotCnt;
    TPanel *pnlAuto07EmptyCnt;
    TPanel *pnlAuto07ICCnt;
    TPanel *palAuto07In;
    TPanel *palAutoInfo08;
    TLabel *lblAuto08Cnt;
    TPanel *palAuto08Bin;
    TButton *btnSetFullTray_Auto8;
    TPanel *palAuto08ID;
    TPanel *palAuto08Cnt;
    TPanel *palAuto08LotCnt;
    TPanel *pnlAuto08EmptyCnt;
    TPanel *pnlAuto08ICCnt;
    TPanel *palAuto08In;
    TPanel *palAutoInfo09;
    TLabel *lblAuto09Cnt;
    TPanel *palAuto09Bin;
    TButton *btnSetFullTray_Auto9;
    TPanel *palAuto09ID;
    TPanel *palAuto09Cnt;
    TPanel *palAuto09LotCnt;
    TPanel *pnlAuto09EmptyCnt;
    TPanel *pnlAuto09ICCnt;
    TPanel *palAuto09In;
    TPanel *palAutoInfo10;
    TLabel *lblAuto10Cnt;
    TPanel *palAuto10Bin;
    TButton *btnSetFullTray_Auto10;
    TPanel *palAuto10ID;
    TPanel *palAuto10Cnt;
    TPanel *palAuto10LotCnt;
    TPanel *pnlAuto10EmptyCnt;
    TPanel *pnlAuto10ICCnt;
    TPanel *palAuto10In;
    TPanel *palAutoInfo01;
    TLabel *lblAuto01Cnt;
    TPanel *palAuto01Bin;
    TButton *btnSetFullTray_Auto1;
    TPanel *palAuto01ID;
    TPanel *palAuto01Cnt;
    TPanel *palAuto01LotCnt;
    TPanel *pnlAuto01ICCnt;
    TPanel *pnlAuto01EmptyCnt;
    TPanel *palAuto01In;
    TPanel *palAutoInfo02;
    TLabel *lblAuto02Cnt;
    TPanel *palAuto02Bin;
    TButton *btnSetFullTray_Auto2;
    TPanel *palAuto02ID;
    TPanel *palAuto02Cnt;
    TPanel *palAuto02LotCnt;
    TPanel *pnlAuto02EmptyCnt;
    TPanel *pnlAuto02ICCnt;
    TPanel *palAuto02In;
    TPanel *palAutoInfo03;
    TLabel *lblAuto03Cnt;
    TPanel *palAuto03Bin;
    TButton *btnSetFullTray_Auto3;
    TPanel *palAuto03ID;
    TPanel *palAuto03Cnt;
    TPanel *palAuto03LotCnt;
    TPanel *pnlAuto03EmptyCnt;
    TPanel *pnlAuto03ICCnt;
    TPanel *palAuto03In;
    TPanel *palAutoInfo04;
    TLabel *lblAuto04Cnt;
    TPanel *palAuto04Bin;
    TButton *btnSetFullTray_Auto4;
    TPanel *palAuto04ID;
    TPanel *palAuto04Cnt;
    TPanel *palAuto04LotCnt;
    TPanel *pnlAuto04ICCnt;
    TPanel *pnlAuto04EmptyCnt;
    TPanel *palAuto04In;
    TPanel *palAutoInfo05;
    TLabel *lblAuto05Cnt;
    TPanel *palAuto05Bin;
    TButton *btnSetFullTray_Auto5;
    TPanel *palAuto05ID;
    TPanel *palAuto05Cnt;
    TPanel *palAuto05LotCnt;
    TPanel *pnlAuto05ICCnt;
    TPanel *pnlAuto05EmptyCnt;
    TPanel *palAuto05In;
    TSpeedButton *btnTranspose;
    TPanel *palTrayArmTray;
    TTMyTray *mtTrayArmTray;
    TPageControl *PageControl1;
    TTabSheet *tsSimulation;
    TTabSheet *tsOtherTool;
    TGroupBox *grpNotUse;
    TLabel *lblNotUse;
    TPanel *palNotUseCnt;
    TPanel *palNotUseBin;
    TPanel *palNotUseID;
    TPanel *palNotUse;
    TTMyTray *myNotUse;
    TPanel *palNoUseIn;
    TPanel *palNoUseICCnt;
    TPanel *palNoUseEmptyCnt;
    TPanel *palNotUseLotCnt;
    TGroupBox *gbSimuSetting;
    TCheckBox *cbEnableSimulation;
    TRadioGroup *rgSimuItems;
    TComboBox *chbSimuSingleArea;
    TButton *btnLoadSimuData;
    void __fastcall sbLaguageClick(TObject *Sender);
    void __fastcall FormShow(TObject *Sender);
    void __fastcall FormClose(TObject *Sender, TCloseAction &Action);
    void __fastcall sbOffsetClick(TObject *Sender);
    void __fastcall sbMessageClick(TObject *Sender);
    void __fastcall btnMainShowClick(TObject *Sender);
    void __fastcall sbMonitorClick(TObject *Sender);
    void __fastcall sbMotorViewClick(TObject *Sender);
    void __fastcall sbMotionViewClick(TObject *Sender);
    void __fastcall sbOtherClick(TObject *Sender);
    void __fastcall sbProductClick(TObject *Sender);
    void __fastcall FormCreate(TObject *Sender);
    void __fastcall cb_WorkFileChange(TObject *Sender);
    void __fastcall sbHomeClick(TObject *Sender);
    void __fastcall sbStartClick(TObject *Sender);
    void __fastcall sbPauseClick(TObject *Sender);
    void __fastcall sbTrayFeedClick(TObject *Sender);
    void __fastcall sbTrayEndClick(TObject *Sender);
    void __fastcall sbOneCycleClick(TObject *Sender);
    void __fastcall sbCleanOutClick(TObject *Sender);
    void __fastcall sbRecordClick(TObject *Sender);
    void __fastcall sbExitClick(TObject *Sender);
    void __fastcall sbMaintanceClick(TObject *Sender);
    void __fastcall sbSpeedClick(TObject *Sender);
    void __fastcall sbToolClick(TObject *Sender);
    void __fastcall Timer1Timer(TObject *Sender);
        void __fastcall sbStoreHangupClick(TObject *Sender);
        void __fastcall Timer2Timer(TObject *Sender);
        void __fastcall pnStartModeClick(TObject *Sender);
        void __fastcall pnRealDummyClick(TObject *Sender);
    void __fastcall cbbUserSelectChange(TObject *Sender);
    void __fastcall sbClearCountClick(TObject *Sender);
    void __fastcall FormDestroy(TObject *Sender);
    void __fastcall AppException(TObject *Sender, Exception *E);                //
    void __fastcall sbTimeDataClick(TObject *Sender);
    void __fastcall spbClearLoadCountClick(TObject *Sender);
    void __fastcall btnTimeEventClick(TObject *Sender);
    void __fastcall cb_WorkFileDropDown(TObject *Sender);
    void __fastcall Panel23MouseDown(TObject *Sender, TMouseButton Button,
          TShiftState Shift, int X, int Y);
    void __fastcall spbTrayStatusClick(TObject *Sender);
    void __fastcall apbLogsClick(TObject *Sender);
    void __fastcall spbStripPosClick(TObject *Sender);
    void __fastcall tmrProductInfoTimer(TObject *Sender);
    void __fastcall sbActionProcessClick(TObject *Sender);
    void __fastcall Button1Click(TObject *Sender);
    void __fastcall sbCCDLearningClick(TObject *Sender);
    void __fastcall btnTrayMapClick(TObject *Sender);
    void __fastcall btnClearTrayClick(TObject *Sender);
    void __fastcall sbPaperSummaryClick(TObject *Sender);
    void __fastcall btnSetBinMatrixClick(TObject *Sender);
    void __fastcall btnSetFullTray_Auto1Click(TObject *Sender);
    void __fastcall lblLoadCurrID_1MouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
    void __fastcall lblLoaderCarIDMouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
    void __fastcall lblMgzCurrID_1MouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
    void __fastcall palAuto01IDMouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
    void __fastcall mtAuto01MouseDown(TObject *Sender, TMouseButton Button,
          TShiftState Shift, int X, int Y);
    void __fastcall btnClearMgz2Click(TObject *Sender);
    void __fastcall btnClearMgz3Click(TObject *Sender);
    void __fastcall btnClearMgz1Click(TObject *Sender);
    void __fastcall mtNowSortTrayMouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
    void __fastcall mtMagNowSortTrayMouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
    void __fastcall btnClearNowLoadClick(TObject *Sender);
    void __fastcall btnClearNowMagClick(TObject *Sender);
    void __fastcall btnLotStartClick(TObject *Sender);
    void __fastcall btnLotEndClick(TObject *Sender);
    void __fastcall edRandomMouseDown(TObject *Sender, TMouseButton Button,
          TShiftState Shift, int X, int Y);
    void __fastcall btnRandomClick(TObject *Sender);
    void __fastcall sbResetClick(TObject *Sender);
    void __fastcall Timer6Timer(TObject *Sender);
    void __fastcall btnAlarmTestClick(TObject *Sender);
    void __fastcall labAutomationDblClick(TObject *Sender);
    void __fastcall mtMag2MouseDown(TObject *Sender, TMouseButton Button,
          TShiftState Shift, int X, int Y);
    void __fastcall btnTransposeClick(TObject *Sender);
    void __fastcall tmrDownCCDTriggerTimer(TObject *Sender);
    void __fastcall rgSimuItemsClick(TObject *Sender);
    void __fastcall btnLoadSimuDataClick(TObject *Sender);
    void __fastcall cbEnableSimulationClick(TObject *Sender);
private:    // User declarations
    void __fastcall SetSimulateScreenStatus();
    void __fastcall UpdateRecordScreen();                                       //Steven 20110827 :重新整理
    TPanel *TrayCTPanel[eTrayCount];
    TPanel *TrayPCAPanel[eTrayCount];
    void EventLogCreate();
    enum eLoaderNo{eSimuNone=0, eSimuOneAuto, eSimuAllAuto, eSimuOneMag, eSimuAllMag, eSimuAllAutoMag, eSimuTotal};
public:     // User declarations
    __fastcall TfMain(TComponent* Owner);
    void __fastcall ScanKey();

    #pragma option push
    BEGIN_MESSAGE_MAP
    END_MESSAGE_MAP(TForm);
    #pragma option pop
    bool fShow;

    void __fastcall SetInitialWindowFrame();
    void __fastcall InitialStringGridLockInfo();
    void __fastcall ShowStringGridLockInfo();
    void __fastcall SetInitialData();

    TSpeedButton *LastClickButton;
    //new version
    void __fastcall UpdateWorkFileComboBox();
    void __fastcall SaveWorkData();
    void __fastcall LoadWorkData();
    void __fastcall StoreHangupData();
    void __fastcall ShowMotorInfo();
    void ShowTaskInfo();

    bool bWakeupGPIBFile;
    bool bWakeupVision;
    void ShowBinCount();
    void ShowLotBinCount(bool bReset=false);

    void ShowProductInfo();
    void CheckContinusStartIsReady();   //Sam 20240710 : 修正 OneCyce 異常
    void AddSuckMessage(AnsiString Msg);
    void __fastcall MainFormChange();   //20131120 wei   led 顯示
    void AddTimeData(int iRow, double Time);

    //Click Event,Auto Save log
    //==>
    void __fastcall SetComponentClick(TWinControl *PCtrl);
    void __fastcall DeletePtr();
    TStringList *BV;
    TList       *BL;
    void __fastcall SaveEventLog(char *Message);
    void __fastcall DeleteEventLog();
    void __fastcall SearchComponentParent(TWinControl *PCtrl,TMyProc *PP);      //搜尋物件上的Parent Path//
    void __fastcall SearchForm();
    //<==
    //Click Event,Auto Save log
    bool ChoiceJobName(AnsiString Data);                                        //kevin 20110317  ASE高雄 要另一執行檔去開啟換TYPE'
    void ShowLoadCarBinCount(AnsiString sStr);
    void CleanBinCount(){MemoBinCount->Lines->Clear();}
    void __fastcall SaveJHT_Log();

    TPanel *tTPanelMot[eTrayCount];                                             //模擬畫面顯示用
    TPanel *tTPanelCnt[eTrayCount];                                             //Auto的總入料數量
    TPanel *tTPanelLotCnt[eTrayCount];                                          //Steven 20240627 : Lot的總入料數量
    TPanel *tTPanelBin[eTrayCount];                                             //Auto的Bin別
    TPanel *tTPanelID[eTrayCount];                                              //Auto Tray的Cilip ID
    TPanel *palEmptyCnt[eTrayCount];                                            //目前Auto上的空格
    TPanel *palLoadCnt[eTrayCount];                                             //目前Auto上的入料數量
    TPanel *palICIn[eTrayCount];                                                //Loader上即將入料的數量
    TTMyTray *mtPanel[eTrayCount];
    
    TPanel *palAutoInfo[eTrack4][eTrackColTotal];                               //Sam 20250911 : 新增 AutoInfo 顯示轉向功能
    TGroupBox *GrpTrack[eTrack4];

    AnsiString sTrayNameEKeeper[eTrayCount];                                    //eKeeper輸出用的名稱
    AnsiString sTrayNameBin[eTrayCount];                                        //Bin to Tray存檔用的名稱
    AnsiString sTrayNameCateData[eTrayCount];                                   //Bin 資料轉為實際生產用的名稱
    AnsiString sTrayNameSpace[eTrayCount];                                      //畫面顯示用的名稱

    AnsiString ekeeperSummary();

    void LoadRunModePicture();
    void LoadStartModePicture();
    TStringList *sHeadList;
    void __fastcall LookForFile();
    void __fastcall Start();
    void SetLotCnt(int iPos,int iCnt);
    void __fastcall ShowOLPState(int iState);
    //mode
    enum RunModeEnum
    {
        HALT=0,
        PAUSE,
        HOMING,
        RUNNING,
        HEATING,
        LOCK,
        EMG,
        MOTOR_OFF,
        ONE_CYCLE,
        CLEAN_OUT,
        TRAY_FEED,
        RUN_CHECK,
        TEACH_NORMAL,
        TEACH_ONECYCLE,
        TEACH_CLEANOUT,
    };
    //version
    enum eMainState
    {
        emsVersion=0,
    };
    void SetLotInTimeOutStart();
    bool GetLotInTimeOut();
    TQPF_Timer tLotInTimeOutDelay;
    bool bNeedChange2OP;
    void SetUserToOP();
    cStateRecord* sr;
    int GetAreaByName(AnsiString sName);
};
//---------------------------------------------------------------------------
extern PACKAGE TfMain *fMain;
extern HAlarm  *Alarm;

//---------------------------------------------------------------------------
#endif

