object dmTrayMotor: TdmTrayMotor
  OldCreateOrder = False
  OnDestroy = DataModuleDestroy
  Left = 1193
  Top = 441
  Height = 165
  Width = 215
  object comTrayStepMotor: TComm
    CommName = 'COM2'
    BaudRate = 115200
    ParityCheck = False
    Outx_CtsFlow = False
    Outx_DsrFlow = False
    DtrControl = DtrEnable
    DsrSensitivity = False
    TxContinueOnXoff = False
    Outx_XonXoffFlow = False
    Inx_XonXoffFlow = False
    ReplaceWhenParityError = False
    IgnoreNullChar = False
    RtsControl = RtsEnable
    XonLimit = 0
    XoffLimit = 0
    ByteSize = _8
    Parity = None
    StopBits = _1
    XonChar = #0
    XoffChar = #0
    ReplacedChar = #0
    ReadIntervalTimeout = 100
    ReadTotalTimeoutMultiplier = 0
    ReadTotalTimeoutConstant = 0
    WriteTotalTimeoutMultiplier = 0
    WriteTotalTimeoutConstant = 0
    Left = 78
    Top = 14
  end
end
