# guard-big5.ps1
# Claude Code PreToolUse hook (matcher: Write|Edit|MultiEdit).
# Purpose: prevent the harness Edit/Write/MultiEdit tools from corrupting legacy
# non-UTF-8 (CP950/Big5) text files. The harness pipeline round-trips file
# content through UTF-8; a legacy Big5 .cpp then comes back with every Chinese
# byte replaced by U+FFFD. This hook blocks the edit BEFORE that happens.
#
# Contract (Claude Code hooks reference, https://code.claude.com/docs/en/hooks):
#   - Receives a JSON object on STDIN.
#   - For Write/Edit/MultiEdit the target path is at tool_input.file_path.
#   - Exit 0  => ALLOW the tool call.
#   - Exit 2  => BLOCK the tool call; stderr text is fed back to Claude as the
#                reason. (This is the version-robust deny mechanism; the
#                JSON-stdout permissionDecision=deny path is only honored on
#                exit 0 and is ignored on exit 2.)
#
# Decision policy (encoding-based, NOT path-based):
#   * file_path empty/missing      -> ALLOW
#   * file does not exist (new)     -> ALLOW
#   * bytes are valid UTF-8         -> ALLOW  (ASCII subset, UTF-8+BOM, UTF-8 CJK)
#   * bytes are NOT valid UTF-8     -> DENY   (legacy CP950/Big5 etc.)
#   * any read/parse error          -> ALLOW  (fail-open; never break the agent)

$ErrorActionPreference = 'Stop'

function Allow { exit 0 }

try {
    # ---- Read and parse the hook payload from STDIN -------------------------
    $raw = [Console]::In.ReadToEnd()
    if ([string]::IsNullOrWhiteSpace($raw)) { Allow }

    try {
        $payload = $raw | ConvertFrom-Json
    } catch {
        # Unparseable stdin -> fail open.
        Allow
    }

    $path = $null
    if ($payload -and $payload.tool_input) {
        $path = $payload.tool_input.file_path
    }

    # file_path empty/missing -> ALLOW
    if ([string]::IsNullOrWhiteSpace($path)) { Allow }

    # New file (does not exist on disk) -> ALLOW
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) { Allow }

    # ---- Read raw bytes (cap at 2 MB for speed) ----------------------------
    $maxBytes = 2MB
    $bytes = $null
    try {
        $fs = [System.IO.File]::Open($path, [System.IO.FileMode]::Open, [System.IO.FileAccess]::Read, [System.IO.FileShare]::ReadWrite)
        try {
            $len = [int][Math]::Min($fs.Length, $maxBytes)
            $bytes = New-Object byte[] $len
            $read = 0
            while ($read -lt $len) {
                $n = $fs.Read($bytes, $read, $len - $read)
                if ($n -le 0) { break }
                $read += $n
            }
            if ($read -lt $len) {
                $tmp = New-Object byte[] $read
                [Array]::Copy($bytes, $tmp, $read)
                $bytes = $tmp
            }
        } finally {
            $fs.Dispose()
        }
    } catch {
        # Read error -> fail open.
        Allow
    }

    # Empty file has no Chinese to corrupt -> ALLOW
    if ($bytes.Length -eq 0) { Allow }

    # ---- Strict UTF-8 validation -------------------------------------------
    # throwOnInvalidBytes=$true makes GetString() throw on any byte sequence
    # that is not well-formed UTF-8. ASCII and UTF-8 (incl. BOM, CJK) pass;
    # CP950/Big5 lead+trail byte pairs are invalid UTF-8 and throw.
    $isValidUtf8 = $true
    try {
        $utf8Strict = [System.Text.UTF8Encoding]::new($false, $true)
        [void]$utf8Strict.GetString($bytes)
    } catch {
        $isValidUtf8 = $false
    }

    if ($isValidUtf8) { Allow }

    # ---- Not valid UTF-8: legacy CP950/Big5 -> DENY (exit 2) ----------------
    $msg = @"
BLOCKED by guard-big5 hook: '$path' is NOT valid UTF-8 (legacy CP950/Big5 / single-byte Chinese encoding).
The harness Edit/Write/MultiEdit tools round-trip content through UTF-8, which would corrupt every Chinese
character in this file into U+FFFD (the replacement character) and silently destroy the source.

Do NOT edit this file with Edit/Write/MultiEdit. Instead edit it via PowerShell using CP950 explicitly:

  `$enc = [System.Text.Encoding]::GetEncoding(950)              # Big5 / CP950
  `$text = `$enc.GetString([System.IO.File]::ReadAllBytes('$path'))
  # ... modify `$text ...
  [System.IO.File]::WriteAllBytes('$path', `$enc.GetBytes(`$text))

NEVER paste codegraph / source-graph output back into this file: that text is already UTF-8-normalized and
will reintroduce U+FFFD corruption. If the file is damaged, restore it from HEAD (git checkout -- '$path').
"@
    [Console]::Error.WriteLine($msg)
    exit 2
}
catch {
    # Any unexpected failure -> fail open so the agent is never broken.
    Allow
}
